### PR TITLE
Review notebook

### PR DESCRIPTION
**Pull request by peterdesmet**

### CODE REVIEW

**Comment by peterdesmet** [comment]
@stijnvanhoey I edited this on binder and then downloaded the file. I do notice however that the output is no longer part of the doc. How can I revert this, so these are included?

**Comment by stijnvanhoey** [comment]
To have the output, rerun on your own machine. I can do that as well.

**Comment by stijnvanhoey** [comment]
Thank for the input, I've checked your comments and rerun the notebook with output; merging here...

**Comment by peterdesmet** [comment]
Oddly enough the  iframe report have no css on loading (but they do on rerunning). Not an issue though.

**Comment by stijnvanhoey** [comment]
I've noticed this as well, but seems ok as the intention is to rerun the code...

**Pull request merged**
